import React from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const PDFReport = ({ reportData, patientName = 'Patient' }) => {
    const generatePDF = async () => {
        // Get patient name from localStorage or use default
        let userEmail = 'Guest User';
        try {
            const userStr = localStorage.getItem('adhd_user');
            if (userStr) {
                const user = JSON.parse(userStr);
                userEmail = user.email || user.name || 'Guest User';
            }
        } catch (e) {
            console.error('Error getting user:', e);
        }

        const reportElement = document.createElement('div');
        reportElement.style.width = '800px';
        reportElement.style.padding = '40px';
        reportElement.style.backgroundColor = 'white';
        reportElement.style.fontFamily = 'Arial, sans-serif';

        reportElement.innerHTML = `
            <div style="text-align: center; margin-bottom: 30px;">
                <h1 style="color: #3b82f6;">🧠 ADHD Clinical Report</h1>
                <p>Generated: ${new Date().toLocaleDateString()}</p>
                <hr style="margin: 20px 0;">
            </div>
            
            <div style="margin-bottom: 25px;">
                <h2 style="color: #1e293b;">📋 Patient Information</h2>
                <p><strong>Patient Name:</strong> ${patientName !== 'خاتون' && patientName !== 'صاحب' ? patientName : userEmail}</p>
                <p><strong>Email:</strong> ${userEmail}</p>
                <p><strong>Age:</strong> ${reportData.age || 'N/A'} years</p>
                <p><strong>Gender:</strong> ${reportData.gender || 'N/A'}</p>
                <p><strong>Assessment Date:</strong> ${new Date().toLocaleDateString()}</p>
            </div>
            
            <div style="margin-bottom: 25px;">
                <h2 style="color: #1e293b;">📊 Risk Assessment</h2>
                <p><strong>Risk Score:</strong> ${reportData.riskScore || 'N/A'}%</p>
                <p><strong>Risk Level:</strong> ${reportData.riskLevel || 'N/A'}</p>
                <p><strong>AI Recommendation:</strong> ${reportData.recommendation || 'N/A'}</p>
            </div>
            
            <div style="margin-bottom: 25px;">
                <h2 style="color: #1e293b;">🔝 Top Symptoms</h2>
                <ul>
                    ${(reportData.topSymptoms || []).slice(0, 10).map(s => `<li>${s.name}: ${s.score}/10</li>`).join('')}
                </ul>
            </div>
            
            <div style="margin-bottom: 25px;">
                <h2 style="color: #1e293b;">✅ Recommended Actions</h2>
                <ul>
                    ${(reportData.whatToDo || []).slice(0, 8).map(item => `<li>${item}</li>`).join('')}
                </ul>
            </div>
            
            <div style="margin-bottom: 25px;">
                <h2 style="color: #1e293b;">🔬 Recommended Tests</h2>
                <ul>
                    ${(reportData.labTests || []).slice(0, 6).map(test => `<li><strong>${test.name}</strong> - ${test.source}<br><small>${test.description || ''}</small></li>`).join('')}
                </ul>
            </div>
            
            <div style="margin-bottom: 25px;">
                <h2 style="color: #1e293b;">📅 Next Steps</h2>
                <ul>
                    ${(reportData.nextSteps || []).map(step => `<li>${step}</li>`).join('')}
                </ul>
            </div>
            
            <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e2e8f0; text-align: center; font-size: 12px; color: #64748b;">
                <p>This is an AI-assisted clinical report. Please consult a healthcare professional for medical advice.</p>
                <p>Data Sources: NIMH, CDC, APA, Mayo Clinic | ADHD Knowledge Graph System</p>
                <p>Report generated by: ${userEmail}</p>
            </div>
        `;

        document.body.appendChild(reportElement);

        try {
            const canvas = await html2canvas(reportElement, {
                scale: 2,
                logging: false,
                useCORS: true
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            const imgWidth = 210;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
            pdf.save(`ADHD_Report_${userEmail.split('@')[0]}_${new Date().toISOString().split('T')[0]}.pdf`);

        } catch (error) {
            console.error('PDF generation error:', error);
            alert('Error generating PDF. Please try again.');
        } finally {
            document.body.removeChild(reportElement);
        }
    };

    return (
        <button onClick={generatePDF} className="pdf-btn">
            📄 Download PDF Report
        </button>
    );
};

export default PDFReport;